"""
Converts lawyer-data CSVs → neo4j/seed.cypher

Usage:
    python lawyer-data/csv_to_cypher.py > neo4j/seed.cypher

Then paste seed.cypher into Neo4j Aura Browser and run it.
The schema.cypher must be applied first (constraints + indexes).
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def escape_cypher(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")


def render_cases(rows: list[dict]) -> list[str]:
    statements = []
    for r in rows:
        if not r.get("citation") or not r.get("short_name"):
            continue
        node_id = slugify(r["short_name"])
        verified = "true" if r.get("verified", "").lower() == "true" else "false"
        stmt = (
            f"MERGE (c:Case {{nodeId: '{escape_cypher(node_id)}'}}) "
            f"SET c.citation  = '{escape_cypher(r['citation'])}', "
            f"    c.shortName = '{escape_cypher(r['short_name'])}', "
            f"    c.year      = {int(r['year']) if r.get('year', '').isdigit() else 0}, "
            f"    c.court     = '{escape_cypher(r.get('court', ''))}', "
            f"    c.status    = '{escape_cypher(r.get('status', 'GOOD_LAW'))}', "
            f"    c.domain    = '{escape_cypher(r.get('domain', 'general'))}', "
            f"    c.verified  = {verified};"
        )
        statements.append(stmt)

        for prop_key in ("proposition_1", "proposition_2"):
            prop = r.get(prop_key, "").strip()
            if prop:
                statements.append(
                    f"MERGE (p:Proposition {{text: '{escape_cypher(prop)}'}}) "
                    f"ON CREATE SET p.domain = '{escape_cypher(r.get('domain', 'general'))}';"
                )
                statements.append(
                    f"MATCH (c:Case {{nodeId: '{escape_cypher(node_id)}'}}), "
                    f"(p:Proposition {{text: '{escape_cypher(prop)}'}}) "
                    f"MERGE (c)-[:ESTABLISHES]->(p);"
                )
    return statements


def render_treatments(rows: list[dict]) -> list[str]:
    statements = []
    for r in rows:
        from_name = r.get("case_from_short_name", "").strip()
        to_name   = r.get("case_to_short_name", "").strip()
        treatment = r.get("treatment", "").strip().upper()
        if not from_name or not to_name or treatment not in {"OVERRULES", "DISTINGUISHES", "DOUBTED_BY"}:
            continue
        from_id = slugify(from_name)
        to_id   = slugify(to_name)
        year    = r.get("year", "0")
        stmt = (
            f"MATCH (a:Case {{nodeId: '{escape_cypher(from_id)}'}}), "
            f"(b:Case {{nodeId: '{escape_cypher(to_id)}'}}) "
            f"MERGE (a)-[:{treatment} {{ "
            f"year: {year if year.isdigit() else 0}, "
            f"court: '{escape_cypher(r.get('court', ''))}', "
            f"context: '{escape_cypher(r.get('context', ''))}'}}]->(b);"
        )
        statements.append(stmt)
    return statements


def render_misapplied(rows: list[dict]) -> list[str]:
    statements = []
    for r in rows:
        short_name = r.get("short_name", "").strip()
        prop_cited = r.get("proposition_cited_in_skeleton", "").strip()
        if not short_name or not prop_cited:
            continue
        node_id = slugify(short_name)
        stmt = (
            f"MATCH (c:Case {{nodeId: '{escape_cypher(node_id)}'}}) "
            f"MERGE (c)-[:MISAPPLIED_AS {{ "
            f"incorrectProposition: '{escape_cypher(prop_cited)}'}}]->(c);"
        )
        statements.append(stmt)
    return statements


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main() -> None:
    cases      = read_csv(ROOT / "cases.csv")
    treatments = read_csv(ROOT / "treatments.csv")
    misapplied = read_csv(ROOT / "misapplied.csv")

    lines = [
        "// CitationGuard — seed.cypher (auto-generated by csv_to_cypher.py)",
        "// Apply schema.cypher first, then run this file in Neo4j Browser.",
        "",
        "// ── Cases ──",
        *render_cases(cases),
        "",
        "// ── Treatment edges ──",
        *render_treatments(treatments),
        "",
        "// ── MISAPPLIED edges ──",
        *render_misapplied(misapplied),
        "",
        "// ── Verification ──",
        "MATCH (c:Case) RETURN count(c) AS total_cases;",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
